ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/bmi160_acc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-$(CONFIG_MTK_BMI160_STC)	:=  bmi160_stc.o

